[input]
url = "https://www.nationstates.net/api/all"
workers = 2

[output.console]
enabled = true
include = ["move"]

[output.file]
enabled = true
path = "akari.log"
maxfiles = 5
threshold = 500
exclude = ["law", "rupdate"]

[output.rmq]
enabled = true
exchange_name = "akari_events"

[output.postgres]
enabled = true
table_name = "akari"
system_table_name = "akari_system"
exclude = ["law", "rupdate"]