[input]
url = "https://www.nationstates.net/api/all"
workers = 2

[output.redis]
enabled = true
url = "redis://0.0.0.0"

[output.console]
enabled = true
include = ["move"]

[output.file]
enabled = true
path = "akari.log"
maxfiles = 5
threshold = 500
exclude = ["law", "rupdate"]

[output.rmq]
enabled = true
url = "amqp://guest:guest@0.0.0.0:5672"
exchange_name = "akari_events"

[output.postgres]
enabled = true
url = "postgres://postgres@127.0.0.1"
table_name = "akari"
system_table_name = "akari_system"
exclude = ["law", "rupdate"]