[input]
url = "https://www.nationstates.net/api/all"
workers = 2

[output.console]
enabled = true
include = ["move"]

[output.file]
enabled = true
path = "akari.log"
maxfiles = 5
threshold = 500
exclude = ["law", "rupdate"]

[output.rmq]
enabled = true

[output.postgres]
enabled = true
exclude = ["law", "rupdate"]